### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by lyrixx**

### CODE REVIEW

**Comment by lyrixx** [comment]
ping @laruence

**Comment by lyrixx** [comment]
ping @jpauli

**Comment by petk** [comment]
Hello, thank you for the typo fix. I guess this got missed and delayed a bit. Anyhow, applied via 0683a614800126ec20ad5901fcb4e151a38d2477 Thanks for making PHP and its ecosystem better.

**Comment by php-pulls** [comment]
**Comment on behalf of petk at php.net:**

.

**Pull request closed without merging**
